version: '3.3'

services:
  pandoc:
    image: patrikfejda/pandoc:latest
    volumes:
      - .:/data
    command: |
      --pdf-engine xelatex
      --listings --toc
      --template eisvogel
      docs.md -o docs.pdf
